PennyLaneAI/PennyLane-IonQ

pennylane_ionq/api_client.py, tests/test_api_client.py
Adds a default timeout to requests of ten minutes.  This is a timeout both on connect and request.  
Without this, it is possible for the polling for complete jobs to hang indefinitely (we observed what we think was this while running against the QPU).
Ten minutes is a rather large timeout and was pulled out of a bag.
=> Add default timeout to requests

.github/workflows/tests.yml, pennylane_ionq/device.py, tests/conftest.py, tests/test_api_client.py, tests/test_device.py
Shots were not being passed to the API, causing all jobs to run 100 shots, the IonQ Default.
I did not see a test of the request structure, let me know if you'd like me to try to add one.
Also not sure on your style for wrapping, so feel free to nit :)
=> Pass shots to IonQ API

pennylane_ionq/device.py
In the case of the actual QPU, instead of resample from the returned results, one should just use the actual samples.  
This is a bit convoluted because the api currently returns probabilities instead of counts, so should be upgraded if/when counts are exposed.
=> Use real samples on QPU device

CHANGELOG.md, pennylane_ionq/device.py, tests/conftest.py, tests/test_api_client.py, tests/test_device.py
Upon locally running the PennyLane device suite tests, I was running into errors involving `ndarray` parameters not being JSON serializable.  So I need to extract the value to being a float.
=> convert parameters to float for serialization

pennylane_ionq/device.py, tests/test_device.py
Alternative to https://github.com/PennyLaneAI/PennyLane-IonQ/pull/49 for supporting more targets.
=> Allow overriding target on device

CHANGELOG.md, pennylane_ionq/device.py, tests/conftest.py
The returned probabilities do not always perfectly sum to one.  This difference seems to be slight, about 1e-5, but it is enough to cause `np.random.choice` to complain.  Therefore we now normalize the probabilities.
=> [Bug] Normalize probabilities

CHANGELOG.md, pennylane_ionq/_version.py
This plugin wasn't released with PennyLane v0.27.0. This reverts the docs updates, and we'll be sure to release it with PennyLane 0.28 instead.
=> Revert "Version Bump (#64)"

doc/conf.py, pennylane_ionq/ops.py
Google is deprecating Universal Analytics on July 1st. This PR replaces that tag with the newer GA4 tag.
=> Switch to GA4

CHANGELOG.md, pennylane_ionq/device.py, requirements-ci.txt
Following the work [here](https://github.com/PennyLaneAI/pennylane/pull/4450/), we make sure that the PennyLane-IonQ plugin supports both operators and defaults to using `StatePrep` where appropriate until it is deprecated.
=> Add support for `StatePrep`

.github/workflows/tests.yml, .readthedocs.yml, CHANGELOG.md, requirements.txt, setup.py
=> Drop Python 3.8 support

CHANGELOG.md, README.rst, doc/devices.rst, pennylane_ionq/__init__.py, pennylane_ionq/device.py, setup.py, tests/conftest.py, tests/test_device.py
use the new `backend` field:
```python
dev = qml.device(
'ionq.qpu',
backend='aria-1',
api_key=api_key,
wires=2,
)
```
to call `qpu.aria-1`
=> Enable qpu.backend for IonQ backends

CHANGELOG.md, pennylane_ionq/api_client.py, pennylane_ionq/device.py, tests/test_api_client.py, tests/test_device.py
This makes retrieving simulator results with the v0.3 interface work. 
I have no hardware access and we run no hardware tests, so I can't promise that this works for hardware.
=> Update to retrieve results with v0.3

.github/workflows/tests.yml, pennylane_ionq/device.py, pennylane_ionq/ops.py, tests/test_api_client.py, tests/test_device.py
=> Add Prod observable support

.github/workflows/tests.yml
This PR is required to update tests to use the latest version of the codecov action (v4.0.0)
More Context: [here](https://about.codecov.io/blog/january-product-update-updating-the-codecov-ci-uploaders-to-the-codecov-cli/)
=> Update to codecov-action v4

CHANGELOG.md, pennylane_ionq/device.py, pennylane_ionq/ops.py, tests/test_device.py
adds a third parameter for the ms gate that defaults to `0.25` (fully entangling). can be changed to enable partial entanglement.
=> enable partially entangling ms gates

README.rst, doc/requirements.txt, pennylane_ionq/device.py
`pennylane.QubitDevice` is deprecated in v0.39, importing `QubitDevice` from `pennylane.devices` instead.
=> `QubitDevice` is now imported from `pennylane.devices`

pennylane_ionq/_version.py, pennylane_ionq/device.py, tests/test_device.py
This is a copy of [this PR](https://github.com/PennyLaneAI/PennyLane-IonQ/pull/121), but on the main repo, to let us run all the tests before merging to master (the other PR is on a fork and doesn't have access to the CI API token)
=> Enable multi circuit submission in PennyLane IonQ

.github/workflows/tests.yml, .github/workflows/upload.yml, .readthedocs.yml, CHANGELOG.md, requirements-ci.txt, requirements.txt, setup.py
=> Removing support for python 3.9 and adding support for python 3.12

.github/workflows/format.yml, .github/workflows/tests.yml, .github/workflows/upload.yml, CHANGELOG.md, pennylane_ionq/_version.py, pennylane_ionq/device.py
**Context:**
`setuptools` has had a release recently that normalizes package names:
References:
- pypa/setuptools#4766
- https://packaging.python.org/en/latest/specifications/name-normalization/#name-normalization
**Description of the Change:**
Due setuptools 75.8.0 and 75.8.1 outputting completely different package names, we cannot support both, so CI now "pins" to >=75.8.1.
**Benefits:**
Fix CI failures.
[sc-85704]
=> Updating `setuptools`

.readthedocs.yml, CHANGELOG.md
**Description of the Change:**
Upgrading the readthedocs.yml runner to Ubuntu-24.04 from Ubuntu22.04; 22.04 is in end of life.
**Benefits:**
The readthedocs runner gets upgrade.
**Possible Drawbacks:**
There could be potential compatibility issues with sphinx and other packages. None were found in the PR run.
**Related GitHub Issues:**
=> Update ubuntu version to 24.04 in readthedocs.yml

doc/devices.rst, pennylane_ionq/_version.py, pennylane_ionq/device.py, tests/test_device.py
Add new IonQ forte-enterprise backend names to tests. Use aria backend instead of harmony as default backend since harmony has been retired.
=> Add new IonQ forte-enterprise backend names to tests.
